Rails.application.routes.draw do
    resources :equipment
    get '/contractors', to: 'contractors#index'
    get '/contractors_sites', to: 'contractors#show_contractor_sites'
    delete '/contractors/:id', to: 'contractors#destroy'
    get '/contractors/:id', to: 'contractors#show'
    delete '/deliveries/:id', to: 'deliveries#destroy' 
    patch '/deliveries/:id', to: 'deliveries#update' 
    post '/deliveries', to: 'deliveries#create'
    get '/equipment_site_contractor/:id', to: 'equipments#show_site_equipment_contractor'
    get '/equipment/site/:id', to: 'equipments#show_site_equipment'
    post '/equipments', to: 'equipments#create'
    get '/equipments/:id', to: 'equipments#show'
    delete '/equipments/:id', to: 'equipments#destroy'
    # create '/managers', to: 'managers#create'
    get '/managers', to: 'managers#index'
    get 'managers/site', to: 'managers#show_manager_sites'
    get '/me', to: 'users#show'
    get '/invitations', to: 'invitations#index'
    post '/invitations', to: 'invitations#create'
    delete '/invitations/:id', to: 'invitations#destroy'
    get '/invitations/site/:site_id', to: 'invitations#show_site_invitations'
    get '/sign_out', to: 'sessions#destroy'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    get '/sites', to: 'sites#index'
    get '/sites/:id', to: 'sites#show'
    post '/sites', to: 'sites#create'
    get '/sites/user', to: 'sites#show_user_sites'
    get '/users', to: 'users#index'
    post '/users', to: 'users#create'
end
